# my global config
global:
  scrape_interval: 5s
  evaluation_interval: 5s
  # scrape_timeout is set to the global default (10s).

rule_files:
  - 'alert.rules'

# alert
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'

scrape_configs:
  - job_name: otel
    honor_labels: true
    static_configs:
      - targets:
          - 'otel-collector:8889'
  - job_name: otel-collector
    honor_labels: true
    static_configs:
      - targets:
          - 'otel-collector:8888'
