{
 "title": "Logging Dashboard via Loki2",
 "description": "Universal and flexible dashboard for logging",
 "tags": [
  "Loki",
  "logging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Env",
    "query": {}
   },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   },
   {
    "name": "app",
    "label": "app",
    "query": {}
   },
   {
    "name": "searchable_pattern",
    "label": "Search (case insensitive)",
    "query": "\"\""
   }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "stat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({env=\"$env\", cluster=~\"$cluster\", app=~\"$app\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $searchable_pattern",
   "type": "stat",
   "description": "Total Count: of $searchable_pattern in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({env=\"$env\", cluster=~\"$cluster\", app=~\"$app\"} |~ \"(?i)$searchable_pattern\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{env=\"$env\", app=~\"$app\", cluster=~\"$cluster\"} |~ \"(?i)$searchable_pattern\" "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({env=\"$env\", app=~\"$app\"})[$__interval])) by (cluster)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" donut",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({env=\"$env\", app=~\"$app\", cluster=~\"$cluster\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({env=\"$env\", cluster=~\"$cluster\", app=~\"$app\"} |~ \"(?i)$searchable_pattern\")[$__interval])) * 100 / sum(count_over_time(({env=\"$env\", cluster=~\"$cluster\", app=~\"$app\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$searchable_pattern\" historical",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time(({env=\"$env\", app=~\"$app\", cluster=~\"$cluster\"} |~ \"(?i)$searchable_pattern\")[$__interval])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "\"$searchable_pattern\" Rate per app",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(({env=\"$env\", cluster=~\"$cluster\", app=~\"$app\"} |~ \"(?i)$searchable_pattern\")[30s])) by (app)",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Logs recieved by level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(app) (count_over_time({cluster=\"$cluster\", env=\"$env\", app=~\"$app\"} | json | _l = `Verbose` [$__interval]))",
     "legendFormat": "{{app}} Verbose"
    },
    {
     "expr": "sum by(app) (count_over_time({cluster=\"$cluster\", env=\"$env\", app=~\"$app\"} | json | _l = `Debug` [$__interval]))",
     "legendFormat": "{{app}} Debug"
    },
    {
     "expr": "sum by(app) (count_over_time({cluster=\"$cluster\", env=\"$env\", app=~\"$app\"} | json | _l = `Information` [$__interval]))",
     "legendFormat": "{{app}} information"
    },
    {
     "expr": "sum by(app) (count_over_time({cluster=\"$cluster\", env=\"$env\", app=~\"$app\"} | json | _l = `Warning` [$__interval]))",
     "legendFormat": "{{app}} Warning"
    },
    {
     "expr": "sum by(app) (count_over_time({cluster=\"$cluster\", env=\"$env\", app=~\"$app\"} | json | _l = `Error` [$__interval]))",
     "legendFormat": "{{app}} Error"
    },
    {
     "expr": "sum by(app) (count_over_time({cluster=\"$cluster\", env=\"$env\", app=~\"$app\"} | json | _l = `Fatal` [$__interval]))",
     "legendFormat": "{{app}} Fatal"
    }
   ]
  }
 ]
}